name: blender-rendering

on:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Blender Install & Render
        run: |
          sh blender.sh
      - name: Add & Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add img
          git commit -m "Generate PNG"
          git pull 
          git push
