on:
  push:

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: |
          sh test.sh
          sudo apt -y update
          sudo apt list --upgradable
          sudo apt install snapd
          sudo snap install blender --classic
          sudo blender --background test.blend --render-output /tmp --engine cycles --render-frame 1

# sudo apt -y install blender blender-data
