name: Latest blog post workflow
on:
  push:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list:
            [
              "http://utan.php.xdomain.jp/blog/rss.xml",
              "https://zenn.dev/u_tan/feed",
            ]
          max_post_count: 8
          disable_sort: true
