name: Latest blog post workflow
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://zenn.dev/u_tan/feed,https://uu-tan.hatenablog.jp/rss"
          max_post_count: 8
          disable_sort: true
